### PR TITLE
Add check for stale terminal price

### PR DESCRIPTION
**Pull request by Chepelau**

### CODE REVIEW

**Comment by Chepelau** [comment]
Currently set for five hours

**Comment by tensojka** [comment]
> Currently set for five hours

Why that much? That could introduce considerable uncertainty for arbitrageurs as they aren't sure which price will actually be used, what would be the downsides of getting it down to say 1 hour?

**Comment by Chepelau** [comment]
No particular reason, I'll make it into one hour, but i guess we need to have a plan in case we have no price

**Comment by Chepelau** [comment]
I'll set it to two hours, since that's when the keeper bots(our and Pragmas) start to set checkpoints

**Comment by Chepelau** [comment]
Good to merge?

**Comment by tensojka** [comment]
Yes

**Pull request merged**
